version: '3'
services:
  demo-app:
    build: .
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      # ホストマシンのポート 8000 を、docker 内のポート 8000 に接続する
      - 8000:8000

  db:
    image: mysql:8.0
    # platform: linux/x86_64  # M1 Mac の場合必要
    environment:
      # パスワードなしで root アカウントを作成
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      # 初期データベースとして demo を設定
      MYSQL_DATABASE: 'demo'

      TZ: 'Asia/Tokyo'
    volumes:
      - mysql_data:/var/lib/mysql

    # MySQL 8.0 ではデフォルトが 'caching_sha2_password' であり、
    # ドライバが非対応のため変更
    # command: --default-authentication-plugin=mysql_native_password
    # ↓
    # 'default_authentication_plugin' is deprecated and will be removed in a future release.
    # Please use authentication_policy instead.
    command: --authentication_policy=mysql_native_password

    ports:
      # ホストマシンのポート 33306 を、docker 内のポート 3306 に接続する
      - 33306:3306

volumes:
  mysql_data:
